//
// Generated file, do not edit! Created by opp_msgtool 6.3 from HCCPacket.msg.
//

#ifndef __INET_HCCPACKET_M_H
#define __INET_HCCPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class HCCPacket;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Enum generated from <tt>HCCPacket.msg:7</tt> by opp_msgtool.
 * <pre>
 * // Enum for Node Roles
 * enum HCCRole
 * {
 *     UNDECIDED = 0;
 *     CLUSTER_HEAD = 1;
 *     CLUSTER_MEMBER = 2;
 * }
 * </pre>
 */
enum HCCRole {
    UNDECIDED = 0,
    CLUSTER_HEAD = 1,
    CLUSTER_MEMBER = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HCCRole& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HCCRole& e) { int n; b->unpack(n); e = static_cast<HCCRole>(n); }

/**
 * Class generated from <tt>HCCPacket.msg:14</tt> by opp_msgtool.
 * <pre>
 * // The Beacon Message extending INET's FieldsChunk (standard for INET 4.5)
 * class HCCPacket extends FieldsChunk
 * {
 *     int srcId;              // The ID of the sender
 *     int degree;             // The sender's connectivity (number of neighbors)
 *     int role;               // The sender's current state (enum HCCRole)
 *     int clusterHeadId;      // Who the sender thinks is the CH (if applicable)
 * }
 * </pre>
 */
class HCCPacket : public ::inet::FieldsChunk
{
  protected:
    int srcId = 0;
    int degree = 0;
    int role = 0;
    int clusterHeadId = 0;

  private:
    void copy(const HCCPacket& other);

  protected:
    bool operator==(const HCCPacket&) = delete;

  public:
    HCCPacket();
    HCCPacket(const HCCPacket& other);
    virtual ~HCCPacket();
    HCCPacket& operator=(const HCCPacket& other);
    virtual HCCPacket *dup() const override {return new HCCPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDegree() const;
    virtual void setDegree(int degree);

    virtual int getRole() const;
    virtual void setRole(int role);

    virtual int getClusterHeadId() const;
    virtual void setClusterHeadId(int clusterHeadId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HCCPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HCCPacket& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::HCCPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::HCCPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_HCCPACKET_M_H

